import { ok, fail, requireFields, isEmail, persist } from "@/lib/api";

/**
 * Membership (Ahli Empati) registration → Supabase `members`.
 * Membership number (AE-YYYY-####) is generated by a DB trigger.
 */
export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}));
  const missing = requireFields(body, ["name", "email", "phone"]);
  if (missing.length) return fail(`Medan wajib tidak lengkap: ${missing.join(", ")}`);
  if (!isEmail(body.email)) return fail("Alamat e-mel tidak sah.");

  const result = await persist("members", {
    name: body.name,
    email: body.email,
    phone: body.phone,
    location: body.location ?? null,
    referral: body.referral ?? null,
    status: "pending",
  });
  if (result !== "ok" && result !== "demo") return fail("Ralat pangkalan data. Sila cuba lagi.", 500);

  return ok("Pendaftaran keahlian diterima. Kami akan menghubungi anda tidak lama lagi.");
}
